import { DomainConfig, DomainType } from './types';
import { generateVector, projectVectorTo2D } from './vectorEngine';

export const DOMAIN_CONFIGS: Record<DomainType, DomainConfig> = {
  animals: {
    id: 'animals',
    label: 'Animals & Motion',
    icon: 'PawPrint',
    description: 'Explore semantic closeness between canine taxonomy, feline predators, movement speed, and resting behavior.',
    dimensions: ['Canine Classification', 'Speed & Agility', 'Feline & Predators', 'Rest & Slumber'],
    samplePrompts: [
      { query: 'speedy dog', explanation: 'Synonym test — Keyword misses "quick canine" (0%), Vector gets >85% match!' },
      { query: 'hungry puppy', explanation: 'Age & species concept — Maps young canine near food bowls & playful pups.' },
      { query: 'lazy feline', explanation: 'Rest concept — Connects "feline" with "cat", "kitten", & "napping".' },
      { query: 'wild wolf pack', explanation: 'Predator concept — Connects canine hunting packs with savannah predators.' },
    ],
    challenge: {
      targetQuery: 'speedy dog',
      description: 'Search for "speedy dog" — watch Keyword Search get 0% on "quick canine", while Vector Search gets >85%!',
      hint: 'Keywords look for exact letters "speedy" and "dog", but vectors understand "quick" = "speedy" and "canine" = "dog"!',
    },
    defaultDocs: [
      {
        id: 'doc-a1',
        title: 'Quick Canine Field Run',
        content: 'Quick canine running across the open field at high speed with agility',
        domain: 'animals',
        vector: [0.92, 0.95, -0.10, 0.05],
        coords: projectVectorTo2D([0.92, 0.95, -0.10, 0.05]),
      },
      {
        id: 'doc-a2',
        title: 'Fast Hound Tennis Chase',
        content: 'Fast hound chasing a bouncy tennis ball with high energy across the grass',
        domain: 'animals',
        vector: [0.88, 0.90, -0.15, 0.10],
        coords: projectVectorTo2D([0.88, 0.90, -0.15, 0.10]),
      },
      {
        id: 'doc-a3',
        title: 'Lazy Feline Sun Nap',
        content: 'Lazy feline napping peacefully under the warm afternoon sun on a patio',
        domain: 'animals',
        vector: [0.90, -0.75, 0.85, 0.88],
        coords: projectVectorTo2D([0.90, -0.75, 0.85, 0.88]),
      },
      {
        id: 'doc-a4',
        title: 'Sleeping Kitten Blanket',
        content: 'Sleeping kitten resting gently on a soft knitted wool blanket indoors',
        domain: 'animals',
        vector: [0.85, -0.80, 0.88, 0.92],
        coords: projectVectorTo2D([0.85, -0.80, 0.88, 0.92]),
      },
      {
        id: 'doc-a5',
        title: 'Hungry Puppy Food Bowl',
        content: 'Hungry puppy waiting patiently near the freshly filled food bowl',
        domain: 'animals',
        vector: [0.90, 0.30, -0.10, 0.40],
        coords: projectVectorTo2D([0.90, 0.30, -0.10, 0.40]),
      },
      {
        id: 'doc-a6',
        title: 'Playful Lake Retriever Pup',
        content: 'Playful golden retriever puppy splashing happily in the shallow lake water',
        domain: 'animals',
        vector: [0.94, 0.45, -0.20, 0.25],
        coords: projectVectorTo2D([0.94, 0.45, -0.20, 0.25]),
      },
      {
        id: 'doc-a7',
        title: 'Sprinting Savannah Predator',
        content: 'Wild sprinting cheetah dashing across the open grassland terrain at top speed',
        domain: 'animals',
        vector: [-0.30, 0.98, 0.95, -0.30],
        coords: projectVectorTo2D([-0.30, 0.98, 0.95, -0.30]),
      },
      {
        id: 'doc-a8',
        title: 'Slumbering Mountain Bear',
        content: 'Slumbering giant grizzly bear hibernating inside a cold mountain cave',
        domain: 'animals',
        vector: [-0.20, -0.85, 0.80, 0.95],
        coords: projectVectorTo2D([-0.20, -0.85, 0.80, 0.95]),
      },
    ],
  },

  ecommerce: {
    id: 'ecommerce',
    label: 'E-Commerce Catalog',
    icon: 'ShoppingBag',
    description: 'Compare real-world product queries for outerwear apparel, weather insulation, and active sports gear.',
    dimensions: ['Apparel & Outerwear', 'Thermal & Insulation', 'Athletic & Performance', 'All-Weather & Outdoor'],
    samplePrompts: [
      { query: 'warm winter coat', explanation: 'Synonym test — Keyword misses "cozy fleece jacket", Vector gets >85% similarity!' },
      { query: 'waterproof boots', explanation: 'Feature test — Maps outdoor hiking gear and rough weather apparel together.' },
      { query: 'running shirt', explanation: 'Athletic test — Finds lightweight breathable marathon apparel.' },
      { query: 'cozy fleece jacket', explanation: 'Thermal test — Connects soft fleece with winter parkas.' },
    ],
    challenge: {
      targetQuery: 'warm winter coat',
      description: 'Search for "warm winter coat" — Keyword Search gets 0% on "cozy fleece jacket", but Vector Search gets >85%!',
      hint: 'Keywords fail because "coat" != "jacket", but vectors map thermal warmth & apparel concepts together!',
    },
    defaultDocs: [
      {
        id: 'doc-e1',
        title: 'Cozy Fleece Thermal Jacket',
        content: 'Cozy fleece jacket engineered with high thermal insulation for chilly winter weather',
        domain: 'ecommerce',
        vector: [0.90, 0.88, 0.15, 0.30],
        coords: projectVectorTo2D([0.90, 0.88, 0.15, 0.30]),
      },
      {
        id: 'doc-e2',
        title: 'Insulated Blizzard Parka',
        content: 'Heavy insulated parka built for extreme freezing snowstorms and sub-zero temperatures',
        domain: 'ecommerce',
        vector: [0.92, 0.98, 0.10, 0.65],
        coords: projectVectorTo2D([0.92, 0.98, 0.10, 0.65]),
      },
      {
        id: 'doc-e3',
        title: 'Lightweight Breathable Runner Tee',
        content: 'Lightweight breathable moisture-wicking shirt engineered for summer marathon sprinters',
        domain: 'ecommerce',
        vector: [0.85, -0.60, 0.95, 0.20],
        coords: projectVectorTo2D([0.85, -0.60, 0.95, 0.20]),
      },
      {
        id: 'doc-e4',
        title: 'Rugged Waterproof Trail Boots',
        content: 'Waterproof rugged leather footwear built for steep rocky mountain hiking trails',
        domain: 'ecommerce',
        vector: [0.80, 0.30, 0.70, 0.98],
        coords: projectVectorTo2D([0.80, 0.30, 0.70, 0.98]),
      },
      {
        id: 'doc-e5',
        title: 'Casual Cotton Summer Top',
        content: 'Soft breathable cotton t-shirt designed for daily relaxed casual lounge wear',
        domain: 'ecommerce',
        vector: [0.95, -0.40, 0.20, -0.30],
        coords: projectVectorTo2D([0.95, -0.40, 0.20, -0.30]),
      },
      {
        id: 'doc-e6',
        title: 'Thermal Alpine Ski Gloves',
        content: 'Insulated waterproof winter gloves specialized for high-speed alpine downhill skiing',
        domain: 'ecommerce',
        vector: [0.85, 0.90, 0.60, 0.70],
        coords: projectVectorTo2D([0.85, 0.90, 0.60, 0.70]),
      },
      {
        id: 'doc-e7',
        title: 'Cushioned Sprinter Sneakers',
        content: 'Flexible ultralight running shoes engineered for high-performance track sprinters',
        domain: 'ecommerce',
        vector: [0.70, -0.30, 0.98, 0.40],
        coords: projectVectorTo2D([0.70, -0.30, 0.98, 0.40]),
      },
    ],
  },

  movies: {
    id: 'movies',
    label: 'Movie Recommendations',
    icon: 'Film',
    description: 'Find films by plot themes, mood, and genre concepts rather than exact title matches.',
    dimensions: ['Sci-Fi & Cosmic', 'Mind-Bending & Mystery', 'Comedy & Humor', 'Romance & Emotion'],
    samplePrompts: [
      { query: 'mind-bending space movie', explanation: 'Theme test — Keyword misses "Interstellar Cosmic Journey" (0%), Vector scores >88%!' },
      { query: 'hilarious comedy film', explanation: 'Genre test — Connects funny, rooming house mates, & humor.' },
      { query: 'romantic drama', explanation: 'Emotion test — Maps autumn Paris lovers & heartwarming plots.' },
      { query: 'interstellar sci-fi', explanation: 'Cosmic test — Finds wormholes, black holes, & space travel.' },
    ],
    challenge: {
      targetQuery: 'mind-bending space movie',
      description: 'Search for "mind-bending space movie" — Keyword Search misses "Interstellar journey", Vector Search scores >88%!',
      hint: 'Keywords look for literal words like "movie", whereas vectors connect space, wormholes, and cosmic concepts!',
    },
    defaultDocs: [
      {
        id: 'doc-m1',
        title: 'Interstellar Cosmic Odyssey',
        content: 'Epic interstellar space journey exploring mysterious cosmic wormholes and black holes',
        domain: 'movies',
        vector: [0.98, 0.82, -0.40, 0.20],
        coords: projectVectorTo2D([0.98, 0.82, -0.40, 0.20]),
      },
      {
        id: 'doc-m2',
        title: 'Subconscious Dream Realm',
        content: 'Mind-altering sci-fi thriller navigating deep subconscious dream levels and memory heist',
        domain: 'movies',
        vector: [0.75, 0.98, -0.30, 0.10],
        coords: projectVectorTo2D([0.75, 0.98, -0.30, 0.10]),
      },
      {
        id: 'doc-m3',
        title: 'Hilarious Roommate Spectacle',
        content: 'Hilarious laugh-out-loud comedy film following quirky rooming house mates in London',
        domain: 'movies',
        vector: [-0.40, -0.50, 0.98, 0.10],
        coords: projectVectorTo2D([-0.40, -0.50, 0.98, 0.10]),
      },
      {
        id: 'doc-m4',
        title: 'Golden Autumn Paris Romance',
        content: 'Heartwarming romantic drama following two passionate lovers in Paris during autumn',
        domain: 'movies',
        vector: [-0.20, -0.20, 0.10, 0.98],
        coords: projectVectorTo2D([-0.20, -0.20, 0.10, 0.98]),
      },
      {
        id: 'doc-m5',
        title: 'Galactic Bounty Hunter Mission',
        content: 'Futuristic space western following an elusive bounty hunter across distant outer rim galaxies',
        domain: 'movies',
        vector: [0.90, 0.50, 0.20, -0.40],
        coords: projectVectorTo2D([0.90, 0.50, 0.20, -0.40]),
      },
      {
        id: 'doc-m6',
        title: 'Psychological Time-Loop Puzzle',
        content: 'Mind-bending psychological detective mystery where an investigator relives the same rainy day',
        domain: 'movies',
        vector: [0.30, 0.92, -0.20, 0.70],
        coords: projectVectorTo2D([0.30, 0.92, -0.20, 0.70]),
      },
    ],
  },
};
